# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-30 18:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='urls',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
